// Grow Savings locators (kebab-case values for qabot).
export const GROW = {
  navItem: 'grow-nav-item',
  entryCard: 'grow-entry-card',
  entryAmount: 'grow-entry-amount',
  entryCta: 'grow-entry-cta',
  page: 'grow-page',
  snapshot: 'grow-snapshot',
  amountSection: 'grow-amount-section',
  amountPreset: (id) => `grow-amount-preset-${id}`,
  amountCustomToggle: 'grow-amount-custom-toggle',
  amountCustomInput: 'grow-amount-custom-input',
  exploreAmount: 'grow-explore-amount',
  goalGroup: 'grow-goal-group',
  horizonGroup: 'grow-horizon-group',
  riskGroup: 'grow-risk-group',
  categorySection: 'grow-category-section',
  explanation: 'grow-explanation',
  productsSection: 'grow-products-section',
  platformsSection: 'grow-platforms-section',
  calculatorSection: 'grow-calculator-section',
  sipTab: 'grow-calculator-sip-tab',
  lumpsumTab: 'grow-calculator-lumpsum-tab',
  chart: 'grow-projection-chart',
  safetyNote: 'grow-safety-note',
};
