// RupeeRizz — Government scheme & non-credit support registry (demonstration data).
// Each record is shown as "Potentially relevant", NEVER "Approved". Users must verify
// eligibility on official sources. This data never affects the financial-health score.

export const SCHEMES = [
  // ---------------- STUDENTS ----------------
  {
    id: 'pm-vidyalaxmi',
    scheme_name: 'PM-Vidyalaxmi',
    target_user: 'student',
    category: 'education_support',
    purpose: 'Collateral-free, guarantor-free education loans for meritorious students in top institutions.',
    benefit_type: 'Education loan + interest support',
    amount_range: 'Up to full course fees; 3% interest subvention for loans up to \u20b910 lakh',
    key_conditions: 'Admission to a listed Quality Higher Education Institution (QHEI); family income criteria for subvention.',
    required_documents: 'Admission proof, ID, income certificate, academic records.',
    eligibility_summary: 'Students admitted to notified top institutions across India.',
    official_application_link: 'https://www.pmvidyalaxmi.co.in/',
    source_url: 'https://www.pmvidyalaxmi.co.in/',
    last_verified_date: '2025-06-01',
    tags: ['laptop', 'course', 'higher_studies', 'exam', 'education'],
  },
  {
    id: 'model-education-loan',
    scheme_name: 'Model Education Loan Scheme (IBA)',
    target_user: 'student',
    category: 'education_support',
    purpose: 'Standardised bank education loans for studies in India and abroad.',
    benefit_type: 'Concessional education loan',
    amount_range: 'Need-based; typically up to \u20b910 lakh (India) / \u20b920 lakh (abroad)',
    key_conditions: 'Admission to a recognised course; repayment after a moratorium period.',
    required_documents: 'Admission letter, fee structure, co-applicant KYC, income proof.',
    eligibility_summary: 'Indian students with confirmed admission to recognised courses.',
    official_application_link: 'https://www.vidyalakshmi.co.in/',
    source_url: 'https://www.vidyalakshmi.co.in/',
    last_verified_date: '2025-06-01',
    tags: ['course', 'higher_studies', 'education'],
  },
  {
    id: 'csis',
    scheme_name: 'Central Sector Interest Subsidy Scheme (CSIS)',
    target_user: 'student',
    category: 'subsidy',
    purpose: 'Full interest subsidy during the moratorium period on education loans for economically weaker students.',
    benefit_type: 'Interest subsidy',
    amount_range: 'Interest waived during moratorium for loans up to \u20b97.5 lakh',
    key_conditions: 'Family income up to \u20b94.5 lakh/year; loan under the IBA model scheme without collateral.',
    required_documents: 'Income certificate, loan sanction letter, admission proof.',
    eligibility_summary: 'EWS students with education loans up to \u20b97.5 lakh.',
    official_application_link: 'https://www.vidyalakshmi.co.in/',
    source_url: 'https://www.education.gov.in/',
    last_verified_date: '2025-06-01',
    tags: ['education', 'course', 'higher_studies'],
  },
  {
    id: 'nsp',
    scheme_name: 'National Scholarship Portal (NSP) pathways',
    target_user: 'student',
    category: 'scholarship',
    purpose: 'Single window for central & state scholarships (pre-matric, post-matric, merit, and more).',
    benefit_type: 'Scholarship / grant',
    amount_range: 'Varies by scheme; maintenance + fee reimbursement',
    key_conditions: 'Scheme-specific income, marks, and category criteria.',
    required_documents: 'Aadhaar-linked bank account, marksheets, income certificate, institute verification.',
    eligibility_summary: 'Students meeting the criteria of central/state scholarship schemes.',
    official_application_link: 'https://scholarships.gov.in/',
    source_url: 'https://scholarships.gov.in/',
    last_verified_date: '2025-06-01',
    tags: ['exam', 'course', 'education', 'hostel'],
  },
  {
    id: 'state-scholarship',
    scheme_name: 'State Scholarship (placeholder \u2014 select your state)',
    target_user: 'student',
    category: 'scholarship',
    purpose: 'State governments run additional scholarships and fee-support schemes.',
    benefit_type: 'Scholarship / fee support',
    amount_range: 'Varies by state and scheme',
    key_conditions: 'Residence/domicile of the state; income and category criteria.',
    required_documents: 'Domicile certificate, income certificate, marksheets.',
    eligibility_summary: 'Students domiciled in the respective state.',
    official_application_link: 'https://scholarships.gov.in/',
    source_url: 'https://scholarships.gov.in/',
    last_verified_date: '2025-06-01',
    tags: ['education', 'hostel', 'exam'],
  },
  // ---------------- MICRO-ENTREPRENEURS ----------------
  {
    id: 'mudra',
    scheme_name: 'Pradhan Mantri MUDRA Yojana (PMMY)',
    target_user: 'micro_entrepreneur',
    category: 'business_support',
    purpose: 'Collateral-free loans for non-farm micro & small enterprises via banks/MFIs.',
    benefit_type: 'Concessional / collateral-free loan',
    amount_range: 'Shishu up to \u20b950k; Kishore \u20b950k\u20135 lakh; Tarun \u20b95\u201310 lakh',
    key_conditions: 'Viable micro-enterprise activity; through a lending institution.',
    required_documents: 'ID/address proof, business proof, quotations for equipment.',
    eligibility_summary: 'Non-corporate, non-farm micro and small entrepreneurs.',
    official_application_link: 'https://www.mudra.org.in/',
    source_url: 'https://www.mudra.org.in/',
    last_verified_date: '2025-06-01',
    tags: ['equipment', 'inventory', 'working_capital', 'expansion', 'business'],
  },
  {
    id: 'pmegp',
    scheme_name: "Prime Minister's Employment Generation Programme (PMEGP)",
    target_user: 'micro_entrepreneur',
    category: 'business_support',
    purpose: 'Credit-linked subsidy to set up new micro-enterprises in manufacturing and services.',
    benefit_type: 'Capital subsidy on bank loan',
    amount_range: 'Margin-money subsidy 15\u201335%; projects up to \u20b950 lakh (mfg) / \u20b920 lakh (service)',
    key_conditions: 'New unit; age 18+; EDP training; not availed subsidy under similar schemes.',
    required_documents: 'Project report, ID, education/EDP proof, caste/special-category (if claiming higher subsidy).',
    eligibility_summary: 'Individuals setting up a new viable micro-enterprise.',
    official_application_link: 'https://www.kviconline.gov.in/pmegpeportal/',
    source_url: 'https://www.kviconline.gov.in/pmegpeportal/',
    last_verified_date: '2025-06-01',
    tags: ['equipment', 'expansion', 'business', 'manufacturing'],
  },
  {
    id: 'pm-svanidhi',
    scheme_name: 'PM SVANidhi',
    target_user: 'micro_entrepreneur',
    category: 'business_support',
    purpose: 'Working-capital micro-loans for street vendors with interest subsidy on timely repayment.',
    benefit_type: 'Working-capital loan + interest subsidy',
    amount_range: '\u20b910k \u2192 \u20b920k \u2192 \u20b950k in increasing cycles; 7% interest subsidy',
    key_conditions: 'Street vendor with a certificate of vending / ULB survey record.',
    required_documents: 'Vending certificate/ID, Aadhaar (for scheme processing), bank account.',
    eligibility_summary: 'Urban street vendors recognised by the local body.',
    official_application_link: 'https://pmsvanidhi.mohua.gov.in/',
    source_url: 'https://pmsvanidhi.mohua.gov.in/',
    last_verified_date: '2025-06-01',
    tags: ['inventory', 'working_capital', 'business'],
  },
  {
    id: 'pm-vishwakarma',
    scheme_name: 'PM Vishwakarma',
    target_user: 'micro_entrepreneur',
    category: 'business_support',
    purpose: 'Support for traditional artisans & craftspeople: training, toolkit incentive, and easy credit.',
    benefit_type: 'Toolkit grant + skilling + collateral-free loan',
    amount_range: '\u20b915k toolkit incentive; loans \u20b91 lakh \u2192 \u20b92 lakh at concessional interest',
    key_conditions: 'Engaged in one of 18 notified trades (e.g., tailor, potter, carpenter).',
    required_documents: 'ID, trade proof/self-declaration, bank account.',
    eligibility_summary: 'Artisans and craftspeople in listed traditional trades.',
    official_application_link: 'https://pmvishwakarma.gov.in/',
    source_url: 'https://pmvishwakarma.gov.in/',
    last_verified_date: '2025-06-01',
    tags: ['equipment', 'tools', 'tailoring', 'business', 'skilling'],
  },
  {
    id: 'pmfme',
    scheme_name: 'PMFME (Micro Food Processing Enterprises)',
    target_user: 'micro_entrepreneur',
    category: 'business_support',
    purpose: 'Credit-linked subsidy & support for micro food-processing units (great for home food businesses).',
    benefit_type: 'Capital subsidy on bank loan + support',
    amount_range: '35% capital subsidy up to \u20b910 lakh; seed capital for SHG members',
    key_conditions: 'Micro food-processing activity; DPR through district resource person.',
    required_documents: 'Business/DPR, ID, bank account, food-related proof.',
    eligibility_summary: 'Individuals/SHGs running micro food-processing enterprises.',
    official_application_link: 'https://pmfme.mofpi.gov.in/',
    source_url: 'https://pmfme.mofpi.gov.in/',
    last_verified_date: '2025-06-01',
    tags: ['food', 'equipment', 'packaging', 'inventory', 'business'],
  },
  {
    id: 'day-nrlm-shg',
    scheme_name: 'DAY-NRLM / Self-Help Group (SHG) support',
    target_user: 'micro_entrepreneur',
    category: 'business_support',
    purpose: 'Community-based savings & low-cost credit through Self-Help Groups.',
    benefit_type: 'SHG savings + concessional community credit',
    amount_range: 'Revolving fund + bank linkage; interest subvention for prompt repayment',
    key_conditions: 'Membership of an eligible SHG; regular group savings.',
    required_documents: 'SHG membership records, bank account, ID.',
    eligibility_summary: 'Members of eligible Self-Help Groups (esp. rural women).',
    official_application_link: 'https://aajeevika.gov.in/',
    source_url: 'https://aajeevika.gov.in/',
    last_verified_date: '2025-06-01',
    tags: ['working_capital', 'inventory', 'business', 'community'],
  },
  {
    id: 'cgtmse',
    scheme_name: 'CGTMSE-backed MSME credit',
    target_user: 'micro_entrepreneur',
    category: 'responsible_credit',
    purpose: 'Credit guarantee that lets banks give collateral-free loans to eligible MSMEs.',
    benefit_type: 'Collateral support / credit guarantee',
    amount_range: 'Guarantee cover on loans typically up to \u20b95 crore',
    key_conditions: 'Eligible MSME; loan through a member lending institution.',
    required_documents: 'Business registration/Udyam, financials, project details.',
    eligibility_summary: 'Registered micro & small enterprises seeking collateral-free credit.',
    official_application_link: 'https://www.cgtmse.in/',
    source_url: 'https://www.cgtmse.in/',
    last_verified_date: '2025-06-01',
    tags: ['expansion', 'equipment', 'working_capital', 'business', 'credit'],
  },
];

// Simple, transparent matcher — uses only consented profile data (user type, purpose, state).
export function matchSchemes(profile = {}) {
  const userType = profile.user_type === 'micro_entrepreneur' ? 'micro_entrepreneur' : 'student';
  return SCHEMES.filter((s) => s.target_user === userType).map((s) => {
    const bits = [];
    bits.push(userType === 'student' ? 'you are a student' : 'you run a micro-business');
    if (profile.state) bits.push(`you are in ${profile.state}`);
    if (profile?.finance?.goal_purpose) bits.push(`your goal relates to ${profile.finance.goal_purpose}`);
    return {
      ...s,
      eligibility_status: 'Potentially relevant',
      match_reason: `Shown because ${bits.join(', ')}. Please verify official eligibility.`,
    };
  });
}
